---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/2 8:39
---
---@class GamePanel
local GamePanel =class("GamePanel");

function GamePanel:ctor()
end

function GamePanel:awake()
    GamePanel.inst=self;
    print("GamePanel awake");
    self.blocksGo=ue.findCompRecursion( self.trans,"blocksGo");
    self.blockGo =ue.loadGo("Go/blockImage");
end

function GamePanel:drawBlocks(map)
    local w=#map[1];
    local h =#map;
    for j=1,h do
        for i=1,w do
            local blockGo=  ue.generateGo(self.blockGo,self.blocksGo);
            blockGo:GetComponent("RectTransform").anchoredPosition =Vector2((i-1)*100,(j-1)*100);


            --local blockTable =CS.LuaMonoHelper.GetLuaComp(blockGo,require("game1.sys.blockItem"));
            --print("blockTable",blockTable);
            --blockTable:toggleImg(false);
        end
    end



end


function GamePanel:onDestroy()
    GamePanel.inst =nil;
end

return GamePanel;