---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/2 8:39
---
---@class GamePanel
local GamePanel =class("GamePanel");

function GamePanel:ctor()
end

function GamePanel:awake()
    GamePanel.inst=self;
    print("GamePanel awake");
end


function GamePanel:onDestroy()
    GamePanel.inst =nil;
end

return GamePanel;