---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/2 8:25
---

local LogoPanel =class("LogoPanel");

function LogoPanel:ctor(sceName)
    self.sceName=sceName;
end

function LogoPanel:awake()
    ue.loadScene(self.sceName)
end

return LogoPanel;