---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/2 8:39
---

local MainPanel =class("MainPanel");

function MainPanel:ctor(sceName)
    self.sceName=sceName;
end

function MainPanel:awake()

    ue.loadScene(self.sceName);

    self.enterBtn = ue.findCompRecursion(self.trans, "enterBtn", "Button");
    self.enterBtn.onClick:AddListener(function()
        Main.bigOver();
        ue.loadScene(self.sceName);
    end);
end

return MainPanel;