---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2025/5/10 14:11
---

local blockItem =class("blockItem");

function blockItem:ctor(sceName)

end

function blockItem:start()
    self.img =self.go:GetComponent("Image");
    print("self.img",self.img);
end

function blockItem:toggleImg(isShow)
   -- self.img.enabled =isShow;
end